service: <+pipeline.stages.Deploy_Service.spec.service.name>
frameworkVersion: '2 || 3'

provider:
  name: aws
  runtime: nodejs18.x
functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /tello
          method: get  
package:
  artifact: <+artifact.path>
